name: Bug Report
description: Submit a bug report
labels: ["bug"]
assignees:
  - rylan-justice
body:
  - type: checkboxes
    attributes:
      label: Prerequisite
      description: By checking the box below, you agree to the following
      options:
        - label: I have confirmed that this bug report has [not been submitted](https://github.com/rylan-justice/cessation/issues?q=is:issue+label:bug).
          required: true
  - type: textarea
    attributes:
      label: Summary
      description: Please provide a concise account of what transpired
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduce
      description: Please provide the necessary steps to reproduce the bug
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: Please provide the version you are using
    validations:
      required: true
