name: Bug report
description: Submit a bug report
labels: ["bug"]
assignees:
  - rylan-justice
body:
  - type: textarea
    attributes:
      label: Summary
      description: Please provide a concise account of what transpired.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduce
      description: Please provide the necessary steps to reproduce the bug.
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: Please provide the version you are using.
    validations:
      required: true
