name: Feature request
description: Submit a feature request
labels: ["feature"]
assignees:
  - rylan-justice
body:
  - type: checkboxes
    attributes:
      label: Prerequisite
      description: By checking the box below, you agree to the following.
      options:
        - label: I have confirmed that this feature request has [not been submitted](https://github.com/rylan-justice/cessation/issues?q=is:issue+label:feature)
          required: true
  - type: textarea
    attributes:
      label: Proposal
      description: Please provide a detailed description of the proposed new feature.
    validations:
      required: true
